Civic identity resolver
dialectlabs/sdk pull request #66
Opened 2022-08-31 12:12 UTC by kevinhcolgan

Implement a Civic Identity Resolver package using the @civic/profile library to retrieve Civic profile information

2022-08-31 18:11 UTC, zhelezkov requested changes
looks super solid! minor q and gtg :)

2022-09-01 06:05 UTC, kevinhcolgan commented on packages/identity-civic/src/identity-civic.spec.ts
> +        headline: 'this is my headline'
the 'headline' is an additional profile information that can be set in civic.me:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/37535663/187843133-44a024fa-8568-4f4b-91c3-da29114146eb.png">
I added it here for completeness

2022-09-01 06:11 UTC, kevinhcolgan commented on packages/identity-civic/src/identity-civic.spec.ts
> +      name: '',
good point, I've pushed a change to use the 'rawDomainName' as the default query name in the case of a reverse lookup

2022-09-01 07:39 UTC, kevinhcolgan commented on packages/identity-civic/src/identity-civic.spec.ts
> +      name: '',
on second thoughts, we discussed internally and we think that only things that are present on the Civic profile should be returned. If the dApp wants to use the lookup query as the default then that can be implemented further up the stack

2022-09-01 11:40 UTC, zhelezkov approved these changes
lgtm

2022-09-01 11:40 UTC, zhelezkov commented on packages/identity-civic/src/identity-civic.spec.ts
> +      name: '',
ok, i see your point, sounds good

2022-09-01 14:28 UTC, merged